### PR TITLE
Open Lamprey to configuration

### PR DESCRIPTION
**Pull request by no-reply**
This makes Lamprey configurable, beginning with a simple repository type configuration option. Adds command line arguments with `OptionParser`.

### CODE REVIEW

**Comment by no-reply** [comment]
Partially closes #21. Remaining configuration needed to pass initialization options to custom repositories.

**Comment by no-reply** [comment]
cc: @mjsuhonos I wonder if you have time for design feedback on this?

**Comment by mjsuhonos** [comment]
Will have time this Friday or sometime after next Monday. Desperate to pick this work back up, but in the middle of some big changes at the moment.

**Comment by no-reply** [comment]
@mjsuhonos wondering whether you're still figuring on finding time to review this. If not, I'm fairly happy with the result and will just merge it. :)

**Comment by mjsuhonos** [comment]
Sorry for the delay; :+1: looks great.

**Pull request merged**
